import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const app = readFileSync(new URL('../app.js', import.meta.url), 'utf8');
const sync = readFileSync(new URL('../sync.js', import.meta.url), 'utf8');
const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const mobile = readFileSync(new URL('../mobile.html', import.meta.url), 'utf8');
const mobileJs = readFileSync(new URL('../mobile.js', import.meta.url), 'utf8');
const manifest = readFileSync(new URL('../manifest.webmanifest', import.meta.url), 'utf8');
const sw = readFileSync(new URL('../sw.js', import.meta.url), 'utf8');
const css = readFileSync(new URL('../styles.css', import.meta.url), 'utf8');

assert.match(app, /const APP_VERSION = '5\.3\.12'/, 'APP_VERSION deve estar em v5.3.12');
for (const file of [html, mobile, manifest, sw]) {
  assert.match(file, /5\.3\.12/, 'todos os arquivos publicados devem carregar a versao nova');
}

assert.match(app, /billingNote_/, 'boletos devem salvar observacao individual por unidade');
assert.match(app, /billingNoteLines/, 'boletos devem combinar observacoes gerais e individuais');
assert.match(app, /extraChargeLabel/, 'deve existir descricao para valor adicional individual');
assert.match(app, /extraCharge/, 'deve existir valor adicional individual');
assert.match(app, /extraChargesText/, 'deve existir lista de valores adicionais por unidade');
assert.match(app, /total: water \+ condo \+ service \+ extraCharge \+ fine/, 'valor adicional deve somar no total');
assert.match(app, /\$\{serviceLine\}\$\{extraLine\}/, 'boleto deve mostrar valor adicional separado de multas e outros');
assert.match(app, /data-print-check/, 'boletos devem ter conferencia guiada de impressao');
assert.match(app, /data-print-bill-part/, 'boletos devem imprimir capa, boletos e contracapa separadamente');
assert.match(app, /managerReportMarkup/, 'deve existir relatorio limpo do sindico');
assert.match(app, /executeMonthlyClose = function\(block\)[\s\S]*exportData\(\)/, 'fechamento deve baixar backup antes de executar');
assert.match(app, /delete routes\.financeiro/, 'rota financeiro deve ser removida');

assert.match(app, /calculationMode/, 'tarifa deve salvar modo de calculo');
assert.match(app, /spreadsheet_1938/, 'deve existir opcao de calculo da planilha Bloco 1938');
assert.match(app, /sheetMinimum/, 'modelo da planilha deve salvar minimo');
assert.match(app, /sheetAllowance/, 'modelo da planilha deve salvar franquia em m3');
assert.match(app, /sheetExcess/, 'modelo da planilha deve salvar valor excedente');
assert.match(app, /Planilha Bloco 1938/, 'interface deve mostrar a opcao Planilha Bloco 1938');
assert.match(mobileJs, /spreadsheet_1938/, 'mobile deve calcular pelo modelo da planilha quando ativo');
assert.match(app, /minimumM3/, 'tarifa deve permitir editar limite da tarifa minima');
assert.match(app, /tier1Limit/, 'tarifa deve permitir editar limite da segunda faixa');
assert.match(app, /80\.84/, 'tarifa padrao deve usar minimo de R$ 80,84');
assert.match(app, /8\.37/, 'tarifa padrao deve usar segunda faixa de R$ 8,37');
assert.match(app, /10\.87/, 'tarifa padrao deve usar terceira faixa de R$ 10,87');
assert.match(app, /tariffExampleRowsV539/, 'configuracoes deve mostrar previa de exemplos de tarifa');
assert.match(app, /tariffPeriodsV5311/, 'tarifa deve ter tabela por vigencia');
assert.match(app, /effectiveMonth/, 'tarifa deve salvar mes de vigencia');
assert.match(app, /tariffForMonthV5311/, 'tarifa deve ser escolhida pelo mes da competencia');

assert.match(app, /delete routes\.regras/, 'rota Regras e descontos deve ser removida');
assert.doesNotMatch(html, /data-route="regras"/, 'menu Regras e descontos nao deve aparecer');
assert.match(app, /data-adjustment-center/, 'Leituras deve conter central de lancamentos e ajustes');
assert.match(app, /billingFineNote/, 'deve existir observacao especifica para multas e outros');
assert.match(app, /Abatimento combinado; -15,00/, 'adicionais devem aceitar valores negativos para abatimentos avulsos');
assert.doesNotMatch(html, /data-route="financeiro"/, 'menu Financeiro nao deve aparecer');
assert.match(app, /amountToWordsV53/, 'recibo deve gerar valor por extenso automaticamente');
assert.match(app, /receipt-preview-branded/, 'recibo deve usar layout com marca');
assert.match(sync, /async function remoteInfo/, 'sincronizacao deve consultar data remota');
assert.match(app, /A copia na nuvem|A cópia na nuvem/, 'app deve avisar conflito antes de sobrescrever nuvem');
assert.match(css, /grid-template-columns:repeat\(2,50%\)!important/, 'boletos devem usar grade 2x2 igual');
assert.match(css, /bill-notes p\{[\s\S]*font-size:6\.9px/, 'observacoes dos boletos devem ter fonte maior em tela');
assert.match(app, /cover-simple-kv/, 'capa frontal deve usar informacoes simplificadas');
assert.match(app, /cover-back-inverted/, 'contracapa deve ser invertida');
assert.doesNotMatch(app, /coverSheet\(block, units, index\)\$\{summarySheet\(block, units, index\)\}/, 'ficha tecnica do bloco nao deve entrar na impressao dos boletos');
assert.match(css, /cover-front\{[\s\S]*align-content:start!important/, 'capa frontal deve ficar compacta no topo para nao cortar a proxima leitura');
assert.match(css, /\.bill-copy-manager\{padding-left:8\.5mm!important\}/, 'via do sindico deve ter area maior para grampear');
assert.match(css, /\.bill-copy-resident:before,[\s\S]*\.bill-copy-resident:after[\s\S]*content:none!important/, 'via do morador nao deve receber marca de grampo');
assert.match(mobile, /Leitura in loco/, 'mobile deve ser dedicado a leitura in loco');
assert.doesNotMatch(mobile, /syncMobile|photoBtn|gpsBtn|exportMobile/, 'mobile simplificado nao deve mostrar sincronizacao, fotos, GPS ou backup');
assert.match(mobileJs, /event\.key === 'Enter'/, 'mobile deve salvar com Enter');
assert.match(mobileJs, /markNoAccess/, 'mobile deve permitir marcar sem acesso');
assert.match(mobileJs, /id="aptSearch"/, 'mobile deve ter busca rapida de apartamento');
assert.match(mobileJs, /id="mobileNote"/, 'mobile deve permitir observacao em campo');
assert.match(mobileJs, /id="routeSummary"/, 'mobile deve mostrar resumo da rota');
assert.match(mobileJs, /jumpPending/, 'mobile deve pular para proximo pendente');
assert.match(mobileJs, /reopenReading/, 'mobile deve permitir reabrir leitura salva');
assert.match(mobileJs, /id="noAccessReason"/, 'mobile deve registrar motivo do sem acesso');
assert.match(mobileJs, /id="mobileBackupBtn"/, 'mobile deve permitir baixar BKP no celular');
assert.match(mobileJs, /downloadMobileBackup/, 'mobile deve gerar backup JSON simples');
assert.match(mobile, /id="mobileImportInput"/, 'mobile deve ter seletor de arquivo para upar BKP');
assert.match(mobileJs, /id="mobileImportBtn"/, 'mobile deve mostrar botao de upar BKP');
assert.match(mobileJs, /importMobileBackup/, 'mobile deve restaurar backup JSON');
assert.match(mobileJs, /backupStateFromJson/, 'mobile deve aceitar backup do app completo ou do mobile');
assert.match(mobileJs, /unitHistory/, 'mobile deve mostrar historico rapido por apartamento');
assert.match(mobileJs, /historyMarkup/, 'mobile deve renderizar historico rapido');
assert.match(mobileJs, /tariffForMonth/, 'mobile deve respeitar tarifa por vigencia no historico');
assert.match(html, /data-route="proposta"/, 'menu deve mostrar a proposta comercial');
assert.match(app, /proposalDocumentMarkup/, 'app deve gerar documento de proposta');
assert.match(app, /data-print-proposal/, 'proposta deve ter botao para salvar PDF ou imprimir');
assert.match(app, /assets\/assinatura\.png/, 'proposta deve usar assinatura existente');
assert.match(css, /proposal-document/, 'proposta deve ter estilo proprio para PDF');

console.log('Smoke tests KR2MELO v5.3.12: OK');
